[package]
name = "ch1"
version = "0.0.1"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
log = "0.4"
polyhal = {git = "ssh://git@github.com/xushanpu123/polyhal.git",features = ["kcontext", "boot"]}
buddy_system_allocator = "0.6"
