name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  rust_toolchain: nightly-2023-12-01

jobs:

  make:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache QEMU
        id: cache-qemu
        uses: actions/cache/restore@v4
        with:
          path: qemu_build
          key: qemu-8.1.0-slirp-1

      - name: Download and build QEMU
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        env:
          QEMU_PATH: qemu-8.1.0
          PREFIX: ${{ github.workspace }}/qemu_build
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build libslirp-dev libglib2.0-dev
          wget https://download.qemu.org/$QEMU_PATH.tar.xz && tar -xJf $QEMU_PATH.tar.xz
          cd $QEMU_PATH \
            && ./configure --prefix=$PREFIX --target-list=riscv64-softmmu --enable-slirp \
            && make -j > /dev/null 2>&1 \
            && make install

      - uses: actions/cache/save@v4
        if: steps.cache-qemu.outputs.cache-hit != 'true'
        with:
          path: qemu_build
          key: qemu-8.1.0-slirp-1

      - name: Install QEMU
        shell: bash
        run: |
          echo "$PWD/qemu_build/bin" >> $GITHUB_PATH

      - name: Verify installation
        shell: bash
        run: |
          qemu-system-riscv64 --version

      - uses: actions/checkout@v3

      - name: Build syscall
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package syscall

      - name: usertests
        run: 
          cargo qemu --ch 8  --release

      
